### PR TITLE
Add Door and Window Sensor with Tilt Detection to Beta

### PR DESCRIPTION
**Pull request by mapulu**
I restructured that it works with the newer homeycompose.
Also added the Door and Window Sensor with Tilt Detection (have the device here and tested it myself)
Thank you

### CODE REVIEW

**Comment by markhaehnel** [comment]
LGTM, but that's not for me to decide.

**Comment by mapulu** [comment]
Nope

**Comment by mapulu** [comment]
Nope

**Comment by markhaehnel** [comment]
That's very sad. :(

**Comment by mruiter** [comment]
Will do my best to push it 2 the appstore from phone

**Comment by markhaehnel** [comment]
@mruiter Can we (me and @mapulu) help you with maintaining this repository in any way?

**Comment by mruiter** [comment]
Its pending approval in the appstore since yesterday , Thx Mark btw . 

Yes , The Popp app is mainly based on user pulls that have the devices. I only have the solar siren.
So any help would be perfect. Shoot in youre pulls and ill update the app in the appstore

**Pull request merged**
